// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vmrsblqknvufwmqyguwa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZtcnNibHFrbnZ1ZndtcXlndXdhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzMDEyNzgsImV4cCI6MjA1ODg3NzI3OH0.j5nqncsCWWoJeRjWOgNAvi1bsRfzdCmoMEu4u9qoSy4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);